#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Benchmark Metrics Calculator for Threat Thinker
-----------------------------------------------
Computes precision, recall, and F1 score for benchmarking threat enumeration accuracy.

Definitions:
  accepted = Number of threats correctly identified ("adopted threats")
  outputs  = Total number of threats generated by the model
  gold     = Total number of expected (ground truth) threats

Formulas:
  precision = accepted / outputs
  recall    = accepted / gold
  f1        = 2 * precision * recall / (precision + recall)
"""

import argparse
import json
import sys


def safe_div(n, d):
    """Safely divide two numbers, returning 0.0 if denominator is zero."""
    return 0.0 if d == 0 else n / d


def compute_metrics(accepted, outputs, gold):
    precision = safe_div(accepted, outputs)
    recall = safe_div(accepted, gold)
    f1 = 0.0 if (precision + recall) == 0 else (2 * precision * recall) / (precision + recall)
    return precision, recall, f1


def main():
    parser = argparse.ArgumentParser(
        description="Compute precision, recall, and F1 score for Threat Thinker benchmark results."
    )
    parser.add_argument("-a", "--accepted", type=int, help="Number of accepted (adopted) threats")
    parser.add_argument("-o", "--outputs", type=int, help="Total number of threats generated")
    parser.add_argument("-g", "--gold", type=int, help="Total number of expected (ground truth) threats")
    parser.add_argument("--decimals", type=int, default=4, help="Decimal precision (default: 4)")
    parser.add_argument("--json", action="store_true", help="Output results as JSON")
    args = parser.parse_args()

    a, o, g = args.accepted, args.outputs, args.gold

    try:
        if a is None:
            a = int(input("Accepted (correct threats): ").strip())
        if o is None:
            o = int(input("Outputs (total threats generated): ").strip())
        if g is None:
            g = int(input("Gold (expected threats): ").strip())
    except Exception as e:
        print(f"Input error: {e}", file=sys.stderr)
        sys.exit(1)

    if any(x < 0 for x in (a, o, g)):
        print("Counts must be non-negative.", file=sys.stderr)
        sys.exit(2)
    if a > o:
        print("Accepted cannot exceed total outputs.", file=sys.stderr)
        sys.exit(3)
    if a > g:
        print("Accepted cannot exceed gold (expected threats).", file=sys.stderr)
        sys.exit(4)

    precision, recall, f1 = compute_metrics(a, o, g)
    d = args.decimals

    if args.json:
        print(
            json.dumps(
                {
                    "accepted": a,
                    "outputs": o,
                    "gold": g,
                    "precision": round(precision, d),
                    "recall": round(recall, d),
                    "f1": round(f1, d),
                },
                ensure_ascii=False,
            )
        )
    else:
        fmt = f"{{:.{d}f}}"
        print(f"Accepted: {a}")
        print(f"Outputs : {o}")
        print(f"Gold    : {g}")
        print(f"Precision: {fmt.format(precision)}")
        print(f"Recall   : {fmt.format(recall)}")
        print(f"F1 Score : {fmt.format(f1)}")


if __name__ == "__main__":
    main()
